### PR TITLE
Systemd service integration

### PR DESCRIPTION
**Pull request by mainmachine**
This keeps the workflow of making user changes to /etc/default/xboxdrv, replicates the xboxdrv.conf script in a way that works with systemd, and creates a new EnvironmentFile based on the two. It seems to be working correctly for me! :smiley:

### CODE REVIEW

**Comment by mainmachine** [comment]
on further testing, it looks like everything works, but the service shuts down after a couple of minutes...?

From a user perspective, this is behaving just like it was on 14.10 with upstart. Haven't tested multiple controllers, haven't tested with wired controller, but working correctly with one wireless controller.

**Comment by mainmachine** [comment]
learned that "forking" is not the correct "Type" to use for this kind of service. :D 

changed to "simple", and now it is no longer timing out

**Comment by raelgc** [comment]
@mainmachine Hope you have time to test with 2 wireless controllers :)

I'll pull this request in a separate branch, then I'll create the 15.04 package and upload it to the PPA during this week.

**Comment by mainmachine** [comment]
I can confirm that it works perfectly for two controllers, and I don't expect more would be a problem. :)

Still need to test wired if someone has one to test.

**Comment by raelgc** [comment]
Just adding issue reference: #39

**Pull request merged**
