### PR TITLE
Develop multiple instances 2

### PR DESCRIPTION
**Pull request by BurninTurtles**
this one may work better. treat each controller slot as though it were your only controller when making options and you should be fine. if it works and you like it ill update docs too. i can share my options and config file if need be to help understand

### CODE REVIEW

**Comment by gyates100895** [comment]
i messed up when forking my repository, so it has the commits from the previous pr too. again, my bad lol

**Comment by raelgc** [comment]
Don't worry, buddy!

I usually don't have any additional configs for my wireless gamepads. I just plug them and play.

Will this work if I clone this PR, generate a local package and install it?

**Comment by gyates100895** [comment]
wanna explain that a bit better? lol if i follow, then i dont see why not,assuming that it only takes the latest file versions. however i have only been adding them into my system manually and hae no knowledge of packaging and distribution lol

**Comment by raelgc** [comment]
You can see the latest version of files from a Pull Request clicking in [`Files changed`](https://github.com/raelgc/ubuntu_xboxdrv/pull/36/files) at the top.

Don't worry about packaging and distribution :)

**Comment by gyates100895** [comment]
then what do you mean by generate a local package?

**Comment by gyates100895** [comment]
i do know however is that this latest one has hotplugging working well on 1 seperate computers :) enjoying a break with some fofix lol

**Comment by gyates100895** [comment]
dude, whatever you need to do to try this out do it. i cant believe how its working now lol to address a controller do "sudo initctl xboxdrv ID=vid:pid" substituting pid and vid for your controllers vendor and product. but you shouldnt need to ever. worst thing ive had happen with this is i had to reconnect a controller from swapping too quickly. im assuming thats an artifact of my last functional usb port and pre 2006 hardware though.

**Comment by gyates100895** [comment]
For the record, I have been working on this one more and will remove these to make a final pull later. It's cleaned up and each job file is quite a bit smaller, however that's the only thing right now. I'm working on device file managing per instance before I think its really done. But if you want to have anyone look at this and the other pull, they both work for multiple controllers and hot plugging, with the occasional restart of the parent service or stop of controller job and replug of controller. That being said this pull is better in that that is required less.  I'd really appreciate it. I really think this could work. Like work so well I'm considering making a GUI for default file configuration in Python :)

**Comment by raelgc** [comment]
@gyates100895 I already thought the same (a Python GUI to replace `js-test`)!.

Anyway, you re-work so deep on this that we should create a team repo.

**Comment by gyates100895** [comment]
will push the the final at the moment build tonight after i add comments.  hotplugging works, proper assigning of newly connected controller configs works based on usbid, and id based on available js devices is set. only bug i see is that the controllers reported id and the upstart job id for the instance may not always correspond with what the controllers respective js device actually is. that being said the controllers still work and give input to the system, just not necessarily from their intended device file. current working idea is that only udev rules can fix that, which from what i gather is exactly what rules are for. those may be best left to the individual user to configure as my personal issue with that was that i had to create a new controller profile under fofix. not really a problem, but it can be called undesired behavior depending on what the circumstances are.

**Comment by gyates100895** [comment]
uploading the final one now. i think you'll like it :)

**Comment by raelgc** [comment]
Why you closed it? :)

**Pull request closed without merging**
